<a href="https://colab.research.google.com/github/mil-mik/data-science-bootcamp/blob/master/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.21.6'

### Metody numpy

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

### Tworzymy wielowymiarową Tablicę


#### 1D Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim  # wymiar

1

In [ ]:
x.shape # kształ

(2,)

In [ ]:
x.size  # podaje liczbę elementow tablicy

2

In [ ]:
x.dtype # typ przechowywanych danych

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

#### 2D Array


In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [4]:
x = np.array([[1, 2, 4],[4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]
